[package]
name = "maze_exit"
version = "0.1.0"
authors = ["Davide Canton <davide.canton5@gmail.com>"]
edition = "2021"

[dependencies]
impl_ops = "0.1.1"
itertools = "0.10.1"
image = "0.24.1"
show-image = { version = "0.12.0", features = ["image"] }