[workspace]
members = [
    "crates/lib",
    "crates/bin_common",
    "crates/term",
    "crates/gui",
    "crates/headless"
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.71"
image = "0.25.1"
