[workspace]
members = [
    "crates/lib",
    "crates/bin_common",
    "crates/gui",
    "crates/headless",
]
resolver = "2"

[profile.profiling]
inherits = "release"
debug = 1

[workspace.dependencies]
anyhow = "1.0.71"
image = "0.25.1"
